### PR TITLE
[ci] Add API Scan job

### PR DESCRIPTION
**Pull request by pjcollins**
Context: https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/25351/APIScan-step-by-step-guide-to-setting-up-a-Pipeline

The ApiScan task has been added to pipeline runs against `main`.  This
task should help us identify related issues earlier, rather than having
to wait for a full scan of VS.

### CODE REVIEW

**Comment by pjcollins** [comment]
@grendello The missing symbols issue is resolved for llvm-strip.exe, however the latest results are showing missing symbols for ld.exe - https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9182240&view=logs&j=64f90b83-5b5a-57f8-612c-70e9ad4dc49b&t=5cc8bc58-5609-5f18-d0d0-cc36b9df15cc&l=57

**Comment by jonpryor** [comment]
What's "funny" is that when I build on Windows via `build-llvm.cmd` I don't have *any* `ld.exe` file.  I instead have:

  * `xa-build\windows\llvm\Release\bin\ld.lld.exe`
  * `xa-build\windows\llvm\Release\bin\ld64.lld.exe`
  * `xa-build\windows\llvm\Release\bin\lld{.exe,.pdb}`
  * `xa-build\windows\llvm\Release\bin\lld-link.exe`
  * `xa-build\windows\llvm\Release\bin\wasm-ld.exe`

Of note is that the only file matching the glob `bin\*ld*.pdb` is `bin\lld.pdb`.  (There is also e.g. `lib\lldWasm.pdb` file, which is next to a `libWasm.lib` file, which I can only assume is a static link library.)

Which brings me to @pjcollins ' [comment](https://github.com/xamarin/xamarin-android-binutils/pull/9#issuecomment-1977186931):

> the latest results are showing missing symbols for ld.exe

which raises a question: where is `ld.exe` coming from?

**Comment by jonpryor** [comment]
Relatedly odd is that there is no `ld.exe` within the [`windows\bin` artifacts folder](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9182240&view=artifacts&pathAsName=false&type=publishedArtifacts).  There *is* `lld.exe` and `lld.pdb`.

**Comment by jonpryor** [comment]
@jonpryor [asked](https://github.com/xamarin/xamarin-android-binutils/pull/9#issuecomment-1984775807):

> which raises a question: where is `ld.exe` coming from?

It appears to be coming from `package.sh`, which special-cases/renames `lld` to `ld`:

https://github.com/xamarin/xamarin-android-binutils/blob/9d342d5057d39c0a9c48ce11cdea6694e36b71bc/package.sh#L87-L111

Given that, it might be easiest to mimic b5900173239e3d83cb54ebb89c9e68f46d1eef92 and explicitly copy `lld.pdb` into the artifacts folder.

**Comment by grendello** [comment]
https://github.com/xamarin/xamarin-android-binutils/pull/17 makes changes to ld+ldd+llvm-strip, it might be good to merge it before this PR and rebase here?

**Comment by jonpryor** [comment]
SEL https://portal.microsofticm.com/imp/v3/incidents/incident/480553298/summary has been approved.

Re-running the build; hopefully the API Compliance Scan will succeed now: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9230281&view=results

**Comment by jonpryor** [comment]
```markdown
Context: https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/25351/APIScan-step-by-step-guide-to-setting-up-a-Pipeline
Context: https://portal.microsofticm.com/imp/v3/incidents/incident/480553298/summary

The `APIScan@2` task has been added to pipeline runs against `main`.
This task should help us identify related issues earlier, rather than
having to wait for a full scan of VS.
```

**Pull request merged**
